theme: jekyll-theme-minimal
logo: /headshot_crogers_202010.jpg
title: Christine Rogers - biosketch
description: Research Project Officer, Montreal Neurological Institute, McGill University, Canada
plugins:
    - jemoj
